const translations = {
    en: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Bringing unique, never-before-seen, simple, and casual online board games to life",
        nav_games: "My Games",
        nav_about: "About the Developer",
        section_games: "My Games",
        game_title: "Yodha: Battle Board",
        game_description: "A strategic online multiplayer board game with unique mechanics.",
        footer: "© 2025 Dripredgames. All rights reserved.",
        // yodha.html translations
        yodha_title: "Yodha: Battle Board",
        yodha_subtitle: "Strategic Online Multiplayer Board Game",
        nav_home: "Home",
        nav_terms: "Terms and Conditions",
        nav_privacy: "Privacy Policy",
        section_yodha: "Yodha: Battle Board",
        yodha_description: "Yodha: Battle Board is our first casual board game, localized to support multiple languages worldwide, offering a strategic and engaging online multiplayer experience. Challenge players globally with unique mechanics like the copyrighted 'sandwich' feature. We are actively working on gameplay improvements and updates, with exciting enhancements planned for the coming months.",
        terms_title: "Terms and Conditions",
        terms_updated: "Last Updated: August 14, 2025",
        terms_intro: "Welcome to Yodha: Battle Board ('the App'), a casual, localized online multiplayer board game developed by Dripredgames ('we,' 'us,' or 'our'). This is our first game, designed to be accessible in multiple languages, with ongoing improvements to enhance gameplay. By downloading, installing, or using the App, you agree to be bound by these Terms and Conditions ('Terms'), which are stored locally on your device. If you do not agree with these Terms, please do not use the App.",
        terms_acceptance: "Acceptance of Terms",
        terms_acceptance_text: "By accessing or using the App, you confirm that you are at least 13 years of age (or the minimum age required in your jurisdiction to use online services) and agree to comply with these Terms. If you are under 18, you must have the consent of a parent or legal guardian to use the App.",
        privacy_title: "Privacy Policy",
        privacy_updated: "Last Updated: August 14, 2025",
        privacy_intro: "Dripredgames ('we,' 'us,' or 'our') is committed to protecting your privacy. This Privacy Policy, stored locally on your device, explains how we handle information when you use Yodha: Battle Board ('the App'), our first casual board game, localized for multiple languages worldwide. We do not collect, store, or share any user information, including Guest IDs, chat messages, or game sessions, with any database or third parties. Please read this policy carefully. If you do not agree with this Privacy Policy, please do not use the App.",
        about_title: "About Drip Red Games",
        about_subtitle: "Connecting the World with Unseen Board Game Adventures",
        section_about: "About the Developer",
        about_description: "Hi, I’m Alfred, the creator of Drip Red Games. As an introvert, I’ve often found social gatherings challenging, feeling out of place in a crowd. This inspired me to become an indie game developer, driven by a passion to design innovative board games that offer a fresh, engaging experience. My goal is to craft games that bring people together, spark joy, and provide an escape from awkward social moments, allowing players to connect through unique and creative gameplay. If you have feedback or ideas, reach out at <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Let’s create something extraordinary together!"
    },
    es: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Dando vida a juegos de mesa en línea únicos, nunca antes vistos, simples y casuales",
        nav_games: "Mis Juegos",
        nav_about: "Sobre el Desarrollador",
        section_games: "Mis Juegos",
        game_title: "Yodha: Tablero de Batalla",
        game_description: "Un juego de mesa multijugador en línea estratégico con mecánicas únicas.",
        footer: "© 2025 Dripredgames. Todos los derechos reservados.",
        // yodha.html translations
        yodha_title: "Yodha: Tablero de Batalla",
        yodha_subtitle: "Juego de Mesa Multijugador Estratégico en Línea",
        nav_home: "Inicio",
        nav_terms: "Términos y Condiciones",
        nav_privacy: "Política de Privacidad",
        section_yodha: "Yodha: Tablero de Batalla",
        yodha_description: "Yodha: Tablero de Batalla es nuestro primer juego de mesa casual, localizado para soportar múltiples idiomas en todo el mundo, ofreciendo una experiencia multijugador en línea estratégica y atractiva. Desafía a jugadores globalmente con mecánicas únicas como la función 'sándwich' con derechos de autor. Estamos trabajando activamente en mejoras y actualizaciones del juego, con emocionantes mejoras planeadas para los próximos meses.",
        terms_title: "Términos y Condiciones",
        terms_updated: "Última Actualización: 14 de agosto de 2025",
        terms_intro: "Bienvenido a Yodha: Tablero de Batalla ('la Aplicación'), un juego de mesa multijugador en línea casual y localizado desarrollado por Dripredgames ('nosotros' o 'nuestro'). Este es nuestro primer juego, diseñado para ser accesible en múltiples idiomas, con mejoras continuas para optimizar la jugabilidad. Al descargar, instalar o usar la Aplicación, aceptas estar sujeto a estos Términos y Condiciones ('Términos'), que se almacenan localmente en tu dispositivo. Si no estás de acuerdo con estos Términos, por favor no uses la Aplicación.",
        terms_acceptance: "Aceptación de los Términos",
        terms_acceptance_text: "Al acceder o usar la Aplicación, confirmas que tienes al menos 13 años de edad (o la edad mínima requerida en tu jurisdicción para usar servicios en línea) y aceptas cumplir con estos Términos. Si tienes menos de 18 años, debes contar con el consentimiento de un padre o tutor legal para usar la Aplicación.",
        privacy_title: "Política de Privacidad",
        privacy_updated: "Última Actualización: 14 de agosto de 2025",
        privacy_intro: "Dripredgames ('nosotros' o 'nuestro') está comprometido con proteger tu privacidad. Esta Política de Privacidad, almacenada localmente en tu dispositivo, explica cómo manejamos la información cuando usas Yodha: Tablero de Batalla ('la Aplicación'), nuestro primer juego de mesa casual, localizado para múltiples idiomas en todo el mundo. No recopilamos, almacenamos ni compartimos ninguna información del usuario, incluidos los ID de invitado, mensajes de chat o sesiones de juego, con ninguna base de datos o terceros. Por favor, lee esta política cuidadosamente. Si no estás de acuerdo con esta Política de Privacidad, no uses la Aplicación.",
        about_title: "Sobre Drip Red Games",
        about_subtitle: "Conectando el Mundo con Aventuras de Juegos de Mesa Nunca Vistas",
        section_about: "Sobre el Desarrollador",
        about_description: "Hola, soy Alfred, el creador de Drip Red Games. Como introvertido, a menudo he encontrado desafiantes las reuniones sociales, sintiéndome fuera de lugar en una multitud. Esto me inspiró a convertirme en un desarrollador de juegos independiente, impulsado por una pasión por diseñar juegos de mesa innovadores que ofrezcan una experiencia fresca y atractiva. Mi objetivo es crear juegos que unan a las personas, generen alegría y proporcionen una escapada de momentos sociales incómodos, permitiendo a los jugadores conectarse a través de un juego único y creativo. Si tienes comentarios o ideas, contáctame en <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. ¡Creemos algo extraordinario juntos!"
    },
    fr: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Donner vie à des jeux de société en ligne uniques, jamais vus auparavant, simples et décontractés",
        nav_games: "Mes Jeux",
        nav_about: "À Propos du Développeur",
        section_games: "Mes Jeux",
        game_title: "Yodha : Plateau de Bataille",
        game_description: "Un jeu de société multijoueur en ligne stratégique avec des mécaniques uniques.",
        footer: "© 2025 Dripredgames. Tous droits réservés.",
        // yodha.html translations
        yodha_title: "Yodha : Plateau de Bataille",
        yodha_subtitle: "Jeu de Société Multijoueur Stratégique en Ligne",
        nav_home: "Accueil",
        nav_terms: "Conditions Générales",
        nav_privacy: "Politique de Confidentialité",
        section_yodha: "Yodha : Plateau de Bataille",
        yodha_description: "Yodha : Plateau de Bataille est notre premier jeu de société décontracté, localisé pour prendre en charge plusieurs langues dans le monde entier, offrant une expérience multijoueur en ligne stratégique et captivante. Défiez des joueurs du monde entier avec des mécaniques uniques comme la fonctionnalité 'sandwich' protégée par le droit d'auteur. Nous travaillons activement à l'amélioration du gameplay et à des mises à jour, avec des améliorations excitantes prévues dans les mois à venir.",
        terms_title: "Conditions Générales",
        terms_updated: "Dernière Mise à Jour : 14 août 2025",
        terms_intro: "Bienvenue dans Yodha : Plateau de Bataille ('l'Application'), un jeu de société multijoueur en ligne décontracté et localisé développé par Dripredgames ('nous' ou 'notre'). C'est notre premier jeu, conçu pour être accessible dans plusieurs langues, avec des améliorations continues pour optimiser le gameplay. En téléchargeant, installant ou utilisant l'Application, vous acceptez d'être lié par ces Conditions Générales ('Conditions'), qui sont stockées localement sur votre appareil. Si vous n'êtes pas d'accord avec ces Conditions, veuillez ne pas utiliser l'Application.",
        terms_acceptance: "Acceptation des Conditions",
        terms_acceptance_text: "En accédant ou en utilisant l'Application, vous confirmez que vous avez au moins 13 ans (ou l'âge minimum requis dans votre juridiction pour utiliser des services en ligne) et acceptez de respecter ces Conditions. Si vous avez moins de 18 ans, vous devez avoir le consentement d'un parent ou tuteur légal pour utiliser l'Application.",
        privacy_title: "Politique de Confidentialité",
        privacy_updated: "Dernière Mise à Jour : 14 août 2025",
        privacy_intro: "Dripredgames ('nous' ou 'notre') s'engage à protéger votre vie privée. Cette Politique de Confidentialité, stockée localement sur votre appareil, explique comment nous gérons les informations lorsque vous utilisez Yodha : Plateau de Bataille ('l'Application'), notre premier jeu de société décontracté, localisé pour plusieurs langues dans le monde entier. Nous ne collectons, ne stockons ni ne partageons aucune information d'utilisateur, y compris les identifiants d'invité, les messages de chat ou les sessions de jeu, avec une base de données ou des tiers. Veuillez lire cette politique attentivement. Si vous n'êtes pas d'accord avec cette Politique de Confidentialité, ne utilisez pas l'Application.",
        about_title: "À Propos de Drip Red Games",
        about_subtitle: "Connecter le Monde avec des Aventures de Jeux de Société Inédites",
        section_about: "À Propos du Développeur",
        about_description: "Salut, je suis Alfred, le créateur de Drip Red Games. En tant qu'introverti, j'ai souvent trouvé les rassemblements sociaux difficiles, me sentant hors de place dans une foule. Cela m'a inspiré à devenir un développeur de jeux indépendant, motivé par une passion pour concevoir des jeux de société innovants qui offrent une expérience nouvelle et captivante. Mon objectif est de créer des jeux qui rassemblent les gens, suscitent de la joie et offrent une évasion des moments sociaux gênants, permettant aux joueurs de se connecter à travers un gameplay unique et créatif. Si vous avez des commentaires ou des idées, contactez-moi à <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Créons quelque chose d'extraordinaire ensemble !"
    },
    hi: {
        title: "ड्रिपरेडगेम्स",
        header_title: "ड्रिपरेडगेम्स",
        header_subtitle: "अद्वितीय, पहले कभी न देखे गए, सरल और आकस्मिक ऑनलाइन बोर्ड गेम्स को जीवंत करना",
        nav_games: "मेरे गेम्स",
        nav_about: "डेवलपर के बारे में",
        section_games: "मेरे गेम्स",
        game_title: "योद्धा: बैटल बोर्ड",
        game_description: "अद्वितीय मैकेनिक्स के साथ एक रणनीतिक ऑनलाइन मल्टीप्लेयर बोर्ड गेम।",
        footer: "© 2025 ड्रिपरेडगेम्स। सभी अधिकार सुरक्षित।",
        // yodha.html translations
        yodha_title: "योद्धा: बैटल बोर्ड",
        yodha_subtitle: "रणनीतिक ऑनलाइन मल्टीप्लेयर बोर्ड गेम",
        nav_home: "होम",
        nav_terms: "नियम और शर्तें",
        nav_privacy: "गोपनीयता नीति",
        section_yodha: "योद्धा: बैटल बोर्ड",
        yodha_description: "योद्धा: बैटल बोर्ड हमारा पहला आकस्मिक बोर्ड गेम है, जो विश्व स्तर पर कई भाषाओं का समर्थन करने के लिए स्थानीयकृत है, जो एक रणनीतिक और आकर्षक ऑनलाइन मल्टीप्लेयर अनुभव प्रदान करता है। कॉपीराइटेड 'सैंडविच' फीचर जैसे अद्वितीय मैकेनिक्स के साथ विश्व स्तर पर खिलाड़ियों को चुनौती दें। हम गेमप्ले में सुधार और अपडेट पर सक्रिय रूप से काम कर रहे हैं, जिसमें आने वाले महीनों में रोमांचक सुधारों की योजना है।",
        terms_title: "नियम और शर्तें",
        terms_updated: "आखिरी अपडेट: 14 अगस्त 2025",
        terms_intro: "योद्धा: बैटल बोर्ड ('ऐप') में आपका स्वागत है, जो ड्रिपरेडगेम्स ('हम,' 'हमें,' या 'हमारा') द्वारा विकसित एक आकस्मिक, स्थानीयकृत ऑनलाइन मल्टीप्लेयर बोर्ड गेम है। यह हमारा पहला गेम है, जो कई भाषाओं में सुलभ होने के लिए डिज़ाइन किया गया है, जिसमें गेमप्ले को बेहतर बनाने के लिए निरंतर सुधार किए जा रहे हैं। ऐप को डाउनलोड, इंस्टॉल या उपयोग करके, आप इन नियमों और शर्तों ('नियम') से बाध्य होने के लिए सहमत होते हैं, जो आपके डिवाइस पर स्थानीय रूप से संग्रहीत हैं। यदि आप इन नियमों से सहमत नहीं हैं, तो कृपया ऐप का उपयोग न करें।",
        terms_acceptance: "नियमों की स्वीकृति",
        terms_acceptance_text: "ऐप तक पहुंचने या इसका उपयोग करके, आप पुष्टि करते हैं कि आपकी आयु कम से कम 13 वर्ष है (या आपकी क्षेत्राधिकार में ऑनलाइन सेवाओं का उपयोग करने के लिए आवश्यक न्यूनतम आयु) और आप इन नियमों का पालन करने के लिए सहमत हैं। यदि आप 18 वर्ष से कम आयु के हैं, तो आपको ऐप का उपयोग करने के लिए माता-पिता या कानूनी अभिभावक की सहमति लेनी होगी।",
        privacy_title: "गोपनीयता नीति",
        privacy_updated: "आखिरी अपडेट: 14 अगस्त 2025",
        privacy_intro: "ड्रिपरेडगेम्स ('हम,' 'हमें,' या 'हमारा') आपकी गोपनीयता की रक्षा करने के लिए प्रतिबद्ध है। यह गोपनीयता नीति, जो आपके डिवाइस पर स्थानीय रूप से संग्रहीत है, बताती है कि हम योद्धा: बैटल बोर्ड ('ऐप') का उपयोग करने पर जानकारी को कैसे संभालते हैं, जो हमारा पहला आकस्मिक बोर्ड गेम है, जो विश्व स्तर पर कई भाषाओं के लिए स्थानीयकृत है। हम कोई भी उपयोगकर्ता जानकारी, जिसमें अतिथि आईडी, चैट संदेश, या गेम सत्र शामिल हैं, किसी डेटाबेस या तीसरे पक्ष के साथ संग्रहीत, संग्रह या साझा नहीं करते हैं। कृपया इस नीति को ध्यान से पढ़ें। यदि आप इस गोपनीयता नीति से सहमत नहीं हैं, तो कृपया ऐप का उपयोग न करें।",
        about_title: "ड्रिप रेड गेम्स के बारे में",
        about_subtitle: "विश्व को अनदेखे बोर्ड गेम साहसिक कार्यों से जोड़ना",
        section_about: "डेवलपर के बारे में",
        about_description: "हाय, मैं अल्फ्रेड, ड्रिप रेड गेम्स का निर्माता हूँ। एक अंतर्मुखी के रूप में, मैंने अक्सर सामाजिक समारोहों को चुनौतीपूर्ण पाया है, भीड़ में अपने आप को जगह से बाहर महसूस करता हूँ। इसने मुझे एक स्वतंत्र गेम डेवलपर बनने के लिए प्रेरित किया, जो नवीन बोर्ड गेम्स डिज़ाइन करने के जुनून से प्रेरित है जो एक ताज़ा, आकर्षक अनुभव प्रदान करते हैं। मेरा लक्ष्य ऐसे गेम बनाना है जो लोगों को एक साथ लाएँ, खुशी प्रदान करें और सामाजिक अजीब क्षणों से बचने का एक रास्ता प्रदान करें, जिससे खिलाड़ी अद्वितीय और रचनात्मक गेमप्ले के माध्यम से जुड़ सकें। यदि आपके पास प्रतिक्रिया या विचार हैं, तो <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a> पर संपर्क करें। आइए मिलकर कुछ असाधारण बनाएँ!"
    },
  de: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Einzigartige, noch nie gesehene, einfache und ungezwungene Online-Brettspiele zum Leben erwecken",
        nav_games: "Meine Spiele",
        nav_about: "Über den Entwickler",
        section_games: "Meine Spiele",
        game_title: "Yodha: Kampftafel",
        game_description: "Ein strategisches Online-Multiplayer-Brettspiel mit einzigartigen Mechanismen.",
        footer: "© 2025 Dripredgames. Alle Rechte vorbehalten.",
        // yodha.html translations
        yodha_title: "Yodha: Kampftafel",
        yodha_subtitle: "Strategisches Online-Multiplayer-Brettspiel",
        nav_home: "Startseite",
        nav_terms: "Nutzungsbedingungen",
        nav_privacy: "Datenschutzrichtlinie",
        section_yodha: "Yodha: Kampftafel",
        yodha_description: "Yodha: Kampftafel ist unser erstes Gelegenheits-Brettspiel, das für mehrere Sprachen weltweit lokalisiert ist und ein strategisches und fesselndes Online-Multiplayer-Erlebnis bietet. Fordern Sie Spieler weltweit mit einzigartigen Mechanismen wie der urheberrechtlich geschützten 'Sandwich'-Funktion heraus. Wir arbeiten aktiv an Gameplay-Verbesserungen und Updates, mit spannenden Erweiterungen, die in den kommenden Monaten geplant sind.",
        terms_title: "Nutzungsbedingungen",
        terms_updated: "Zuletzt aktualisiert: 14. August 2025",
        terms_intro: "Willkommen bei Yodha: Kampftafel ('die App'), ein Gelegenheits- und lokalisiertes Online-Multiplayer-Brettspiel, entwickelt von Dripredgames ('wir', 'uns' oder 'unser'). Dies ist unser erstes Spiel, das in mehreren Sprachen zugänglich ist, mit fortlaufenden Verbesserungen, um das Gameplay zu optimieren. Durch das Herunterladen, Installieren oder Nutzen der App erklären Sie sich mit diesen Nutzungsbedingungen ('Bedingungen') einverstanden, die lokal auf Ihrem Gerät gespeichert sind. Wenn Sie mit diesen Bedingungen nicht einverstanden sind, nutzen Sie die App bitte nicht.",
        terms_acceptance: "Akzeptanz der Bedingungen",
        terms_acceptance_text: "Durch den Zugriff auf oder die Nutzung der App bestätigen Sie, dass Sie mindestens 13 Jahre alt sind (oder das in Ihrer Rechtsordnung erforderliche Mindestalter für die Nutzung von Online-Diensten) und erklären sich damit einverstanden, diese Bedingungen einzuhalten. Wenn Sie unter 18 Jahre alt sind, müssen Sie die Zustimmung eines Elternteils oder eines gesetzlichen Vormunds haben, um die App zu nutzen.",
        privacy_title: "Datenschutzrichtlinie",
        privacy_updated: "Zuletzt aktualisiert: 14. August 2025",
        privacy_intro: "Dripredgames ('wir', 'uns' oder 'unser') ist dem Schutz Ihrer Privatsphäre verpflichtet. Diese Datenschutzrichtlinie, die lokal auf Ihrem Gerät gespeichert ist, erläutert, wie wir Informationen verarbeiten, wenn Sie Yodha: Kampftafel ('die App') nutzen, unser erstes Gelegenheits-Brettspiel, das für mehrere Sprachen weltweit lokalisiert ist. Wir sammeln, speichern oder teilen keinerlei Nutzerinformationen, einschließlich Gast-IDs, Chat-Nachrichten oder Spielsitzungen, mit Datenbanken oder Dritten. Bitte lesen Sie diese Richtlinie sorgfältig durch. Wenn Sie mit dieser Datenschutzrichtlinie nicht einverstanden sind, nutzen Sie die App bitte nicht.",
        about_title: "Über Drip Red Games",
        about_subtitle: "Die Welt mit einzigartigen Brettspiel-Abenteuern verbinden",
        section_about: "Über den Entwickler",
        about_description: "Hallo, ich bin Alfred, der Schöpfer von Drip Red Games. Als Introvertierter fand ich gesellschaftliche Zusammenkünfte oft herausfordernd und fühlte mich in Menschenmengen fehl am Platz. Dies inspirierte mich, ein unabhängiger Spieleentwickler zu werden, angetrieben von der Leidenschaft, innovative Brettspiele zu entwerfen, die ein frisches und fesselndes Erlebnis bieten. Mein Ziel ist es, Spiele zu entwickeln, die Menschen zusammenbringen, Freude bereiten und eine Flucht aus unangenehmen sozialen Momenten bieten, indem sie Spielern ermöglichen, sich durch einzigartiges und kreatives Gameplay zu verbinden. Wenn Sie Feedback oder Ideen haben, kontaktieren Sie mich unter <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Lassen Sie uns gemeinsam etwas Außergewöhnliches schaffen!"
    },
    zh: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "将独特、前所未有、简单且休闲的在线棋盘游戏带入生活",
        nav_games: "我的游戏",
        nav_about: "关于开发者",
        section_games: "我的游戏",
        game_title: "Yodha：战斗棋盘",
        game_description: "一款具有独特机制的战略在线多人棋盘游戏。",
        footer: "© 2025 Dripredgames。保留所有权利。",
        // yodha.html translations
        yodha_title: "Yodha：战斗棋盘",
        yodha_subtitle: "战略在线多人棋盘游戏",
        nav_home: "首页",
        nav_terms: "条款与条件",
        nav_privacy: "隐私政策",
        section_yodha: "Yodha：战斗棋盘",
        yodha_description: "Yodha：战斗棋盘是我们的首款休闲棋盘游戏，支持全球多种语言本地化，提供战略性和引人入胜的在线多人游戏体验。使用独特的机制（如受版权保护的“夹心”功能）挑战全球玩家。我们正在积极改进游戏玩法并进行更新，未来几个月计划推出令人兴奋的增强功能。",
        terms_title: "条款与条件",
        terms_updated: "最后更新：2025年8月14日",
        terms_intro: "欢迎体验Yodha：战斗棋盘（以下简称“应用”），这是一款由Dripredgames（“我们”或“我们的”）开发的休闲、本地化的在线多人棋盘游戏。这是我们的首款游戏，设计为支持多种语言，并持续改进以优化游戏体验。通过下载、安装或使用本应用，您同意遵守这些条款与条件（“条款”），这些条款存储在您的设备本地。如果您不同意这些条款，请勿使用本应用。",
        terms_acceptance: "条款接受",
        terms_acceptance_text: "通过访问或使用本应用，您确认您至少年满13岁（或您所在司法管辖区使用在线服务所需的最低年龄），并同意遵守这些条款。如果您未满18岁，您必须获得父母或法定监护人的同意才能使用本应用。",
        privacy_title: "隐私政策",
        privacy_updated: "最后更新：2025年8月14日",
        privacy_intro: "Dripredgames（“我们”或“我们的”）致力于保护您的隐私。本隐私政策存储在您的设备本地，解释了您使用Yodha：战斗棋盘（“应用”）时我们如何处理信息，这是我们的首款休闲棋盘游戏，支持全球多种语言本地化。我们不会收集、存储或与任何数据库或第三方共享任何用户信息，包括访客ID、聊天消息或游戏会话。请仔细阅读本政策。如果您不同意本隐私政策，请勿使用本应用。",
        about_title: "关于Drip Red Games",
        about_subtitle: "通过前所未有的棋盘游戏冒险连接世界",
        section_about: "关于开发者",
        about_description: "你好，我是Alfred，Drip Red Games的创始人。作为一名内向者，我常常觉得社交场合具有挑战性，在人群中感到格格不入。这激励我成为一名独立游戏开发者，出于设计创新棋盘游戏的热情，提供新鲜而引人入胜的体验。我的目标是打造能将人们聚集在一起、带来欢乐并提供摆脱尴尬社交时刻的游戏，让玩家通过独特且富有创意的游戏玩法建立联系。如果您有反馈或想法，请通过<a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>联系我。让我们一起创造非凡的东西！"
    },
    ar: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "إحياء ألعاب الطاولة عبر الإنترنت الفريدة، التي لم تُرَ من قبل، البسيطة والعادية",
        nav_games: "ألعابي",
        nav_about: "عن المطور",
        section_games: "ألعابي",
        game_title: "يوذا: لوحة المعركة",
        game_description: "لعبة طاولة إستراتيجية متعددة اللاعبين عبر الإنترنت بآليات فريدة.",
        footer: "© 2025 Dripredgames. جميع الحقوق محفوظة.",
        // yodha.html translations
        yodha_title: "يوذا: لوحة المعركة",
        yodha_subtitle: "لعبة طاولة إستراتيجية متعددة اللاعبين عبر الإنترنت",
        nav_home: "الصفحة الرئيسية",
        nav_terms: "الشروط والأحكام",
        nav_privacy: "سياسة الخصوصية",
        section_yodha: "يوذا: لوحة المعركة",
        yodha_description: "يوذا: لوحة المعركة هي أول لعبة طاولة عادية لدينا، تم تهيئتها لدعم لغات متعددة حول العالم، وتقدم تجربة متعددة اللاعبين عبر الإنترنت إستراتيجية وجذابة. تحدَّ اللاعبين عالميًا بآليات فريدة مثل ميزة 'الساندويتش' المحمية بحقوق الطبع والنشر. نحن نعمل بنشاط على تحسينات اللعب والتحديثات، مع تحسينات مثيرة مخطط لها في الأشهر القادمة.",
        terms_title: "الشروط والأحكام",
        terms_updated: "آخر تحديث: 14 أغسطس 2025",
        terms_intro: "مرحبًا بك في يوذا: لوحة المعركة ('التطبيق')، وهي لعبة طاولة متعددة اللاعبين عبر الإنترنت عادية ومحلية تم تطويرها بواسطة Dripredgames ('نحن' أو 'لنا'). هذه هي لعبتنا الأولى، مصممة لتكون متاحة بلغات متعددة، مع تحسينات مستمرة لتعزيز اللعب. بتنزيل التطبيق أو تثبيته أو استخدامه، فإنك توافق على الالتزام بهذه الشروط والأحكام ('الشروط')، التي يتم تخزينها محليًا على جهازك. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام التطبيق.",
        terms_acceptance: "قبول الشروط",
        terms_acceptance_text: "من خلال الوصول إلى التطبيق أو استخدامه، فإنك تؤكد أن عمرك 13 عامًا على الأقل (أو الحد الأدنى للسن المطلوب في ولايتك القضائية لاستخدام الخدمات عبر الإنترنت) وتوافق على الالتزام بهذه الشروط. إذا كنت أقل من 18 عامًا، يجب أن تحصل على موافقة أحد الوالدين أو الوصي القانوني لاستخدام التطبيق.",
        privacy_title: "سياسة الخصوصية",
        privacy_updated: "آخر تحديث: 14 أغسطس 2025",
        privacy_intro: "Dripredgames ('نحن' أو 'لنا') ملتزمون بحماية خصوصيتك. تشرح سياسة الخصوصية هذه، المخزنة محليًا على جهازك، كيفية تعاملنا مع المعلومات عند استخدامك ليوذا: لوحة المعركة ('التطبيق')، وهي أول لعبة طاولة عادية لدينا، تم تهيئتها للغات متعددة حول العالم. لا نجمع أو نخزن أو نشارك أي معلومات مستخدم، بما في ذلك معرفات الضيوف، رسائل الدردشة، أو جلسات اللعب، مع أي قاعدة بيانات أو أطراف ثالثة. يرجى قراءة هذه السياسة بعناية. إذا كنت لا توافق على سياسة الخصوصية هذه، يرجى عدم استخدام التطبيق.",
        about_title: "عن Drip Red Games",
        about_subtitle: "ربط العالم بمغامرات ألعاب الطاولة غير المسبوقة",
        section_about: "عن المطور",
        about_description: "مرحبًا، أنا ألفريد، مبتكر Drip Red Games. كشخص انطوائي، غالبًا ما وجدت التجمعات الاجتماعية صعبة، وشعرت بأنني خارج المكان في الحشود. هذا ألهمني لأصبح مطور ألعاب مستقل، مدفوعًا بشغف لتصميم ألعاب طاولة مبتكرة تقدم تجربة جديدة وجذابة. هدفي هو صنع ألعاب تجمع الناس، تثير الفرح، وتوفر هروبًا من اللحظات الاجتماعية المحرجة، مما يتيح للاعبين التواصل من خلال لعب مبتكر وإبداعي. إذا كانت لديك تعليقات أو أفكار، تواصل معي عبر <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. دعنا نصنع شيئًا استثنائيًا معًا!"
    },
    ru: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Оживление уникальных, никогда ранее не виданных, простых и казуальных онлайн-настольных игр",
        nav_games: "Мои игры",
        nav_about: "О разработчике",
        section_games: "Мои игры",
        game_title: "Йодха: Боевая доска",
        game_description: "Стратегическая онлайн-мультиплеерная настольная игра с уникальными механиками.",
        footer: "© 2025 Dripredgames. Все права защищены.",
        // yodha.html translations
        yodha_title: "Йодха: Боевая доска",
        yodha_subtitle: "Стратегическая онлайн-мультиплеерная настольная игра",
        nav_home: "Главная",
        nav_terms: "Условия использования",
        nav_privacy: "Политика конфиденциальности",
        section_yodha: "Йодха: Боевая доска",
        yodha_description: "Йодха: Боевая доска — наша первая казуальная настольная игра, локализованная для поддержки нескольких языков по всему миру, предлагающая стратегический и увлекательный онлайн-мультиплеерный опыт. Бросайте вызов игрокам по всему миру с уникальными механиками, такими как защищённая авторским правом функция 'сэндвич'. Мы активно работаем над улучшениями геймплея и обновлениями, с захватывающими улучшениями, запланированными на ближайшие месяцы.",
        terms_title: "Условия использования",
        terms_updated: "Последнее обновление: 14 августа 2025 года",
        terms_intro: "Добро пожаловать в Йодха: Боевая доска ('Приложение'), казуальную и локализованную онлайн-мультиплеерную настольную игру, разработанную Dripredgames ('мы', 'нас' или 'наш'). Это наша первая игра, разработанная для доступности на нескольких языках с постоянными улучшениями для оптимизации геймплея. Загружая, устанавливая или используя Приложение, вы соглашаетесь соблюдать настоящие Условия использования ('Условия'), которые хранятся локально на вашем устройстве. Если вы не согласны с этими Условиями, пожалуйста, не используйте Приложение.",
        terms_acceptance: "Принятие условий",
        terms_acceptance_text: "Заходя в Приложение или используя его, вы подтверждаете, что вам не менее 13 лет (или минимальный возраст, требуемый в вашей юрисдикции для использования онлайн-сервисов), и соглашаетесь соблюдать настоящие Условия. Если вам меньше 18 лет, вы должны получить согласие родителя или законного опекуна для использования Приложения.",
        privacy_title: "Политика конфиденциальности",
        privacy_updated: "Последнее обновление: 14 августа 2025 года",
        privacy_intro: "Dripredgames ('мы', 'нас' или 'наш') стремится защищать вашу конфиденциальность. Настоящая Политика конфиденциальности, хранящаяся локально на вашем устройстве, объясняет, как мы обрабатываем информацию, когда вы используете Йодха: Боевая доска ('Приложение'), нашу первую казуальную настольную игру, локализованную для нескольких языков по всему миру. Мы не собираем, не храним и не передаём никакую информацию пользователей, включая идентификаторы гостей, сообщения чата или игровые сессии, в базы данных или третьим лицам. Пожалуйста, внимательно прочитайте эту политику. Если вы не согласны с этой Политикой конфиденциальности, пожалуйста, не используйте Приложение.",
        about_title: "О Drip Red Games",
        about_subtitle: "Соединение мира с невиданными приключениями в настольных играх",
        section_about: "О разработчике",
        about_description: "Привет, я Альфред, создатель Drip Red Games. Как интроверт, я часто находил социальные собрания сложными, чувствуя себя не в своей тарелке в толпе. Это вдохновило меня стать независимым разработчиком игр, движимым страстью к созданию инновационных настольных игр, которые предлагают свежий и увлекательный опыт. Моя цель — создавать игры, которые объединяют людей, приносят радость и позволяют уйти от неловких социальных моментов, давая игрокам возможность соединяться через уникальный и креативный геймплей. Если у вас есть отзывы или идеи, свяжитесь со мной по адресу <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Давай создадим что-то необыкновенное вместе!"
    },
    ja: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "ユニークでこれまでにないシンプルでカジュアルなオンラインボードゲームを創造する",
        nav_games: "私のゲーム",
        nav_about: "開発者について",
        section_games: "私のゲーム",
        game_title: "ヨーダ：バトルボード",
        game_description: "独自のメカニクスを持つ戦略的なオンラインマルチプレイヤーボードゲーム。",
        footer: "© 2025 Dripredgames. All rights reserved.",
        // yodha.html translations
        yodha_title: "ヨーダ：バトルボード",
        yodha_subtitle: "戦略的なオンラインマルチプレイヤーボードゲーム",
        nav_home: "ホーム",
        nav_terms: "利用規約",
        nav_privacy: "プライバシーポリシー",
        section_yodha: "ヨーダ：バトルボード",
        yodha_description: "ヨーダ：バトルボードは、世界中で複数の言語に対応した私たちの最初のカジュアルボードゲームで、戦略的で魅力的なオンラインマルチプレイヤー体験を提供します。著作権で保護された「サンドイッチ」機能などの独自のメカニクスで、世界中のプレイヤーに挑戦してください。私たちはゲームプレイの改善とアップデートに積極的に取り組んでおり、今後数ヶ月でエキサイティングな強化を予定しています。",
        terms_title: "利用規約",
        terms_updated: "最終更新：2025年8月14日",
        terms_intro: "ヨーダ：バトルボード（以下「アプリ」）へようこそ。これは、Dripredgames（「私たち」または「当社」）が開発したカジュアルでローカライズされたオンラインマルチプレイヤーボードゲームです。これは私たちの最初のゲームで、複数の言語でアクセス可能に設計されており、ゲームプレイを最適化するための継続的な改善が行われています。アプリをダウンロード、インストール、または使用することで、これらの利用規約（「規約」）に拘束されることに同意するものとします。これらの規約はデバイスにローカルに保存されます。これらの規約に同意しない場合、アプリを使用しないでください。",
        terms_acceptance: "規約の受諾",
        terms_acceptance_text: "アプリにアクセスまたは使用することで、あなたは少なくとも13歳以上（またはあなたの管轄区域でオンラインサービスを使用するために必要な最低年齢）であり、これらの規約を遵守することに同意することを確認します。18歳未満の場合、親または法定後見人の同意を得てアプリを使用する必要があります。",
        privacy_title: "プライバシーポリシー",
        privacy_updated: "最終更新：2025年8月14日",
        privacy_intro: "Dripredgames（「私たち」または「当社」）はあなたのプライバシーの保護に取り組んでいます。このプライバシーポリシーは、デバイスにローカルに保存されており、ヨーダ：バトルボード（「アプリ」）を使用する際の情報の取り扱いについて説明します。これは、複数の言語に対応した私たちの最初のカジュアルボードゲームです。ゲストID、チャットメッセージ、ゲームセッションを含むいかなるユーザー情報も、データベースや第三者と収集、保存、共有しません。このポリシーをよくお読みください。このプライバシーポリシーに同意しない場合、アプリを使用しないでください。",
        about_title: "Drip Red Gamesについて",
        about_subtitle: "これまでにないボードゲームの冒険で世界をつなぐ",
        section_about: "開発者について",
        about_description: "こんにちは、私はDrip Red Gamesの創設者、アルフレッドです。内向的な性格のため、社交的な集まりはしばしば難しく、群衆の中で場違いに感じることがありました。これが私をインディーゲーム開発者になるよう駆り立て、革新的なボードゲームをデザインする情熱から、新鮮で魅力的な体験を提供しています。私の目標は、人々を一つにし、喜びをもたらし、気まずい社交の瞬間から逃れるゲームを作り、ユニークで創造的なゲームプレイを通じてプレイヤーがつながることを可能にすることです。フィードバックやアイデアがあれば、<a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>までご連絡ください。一緒に何か特別なものを作りましょう！"
    },
    pt: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Trazendo jogos de tabuleiro online únicos, nunca antes vistos, simples e casuais à vida",
        nav_games: "Meus Jogos",
        nav_about: "Sobre o Desenvolvedor",
        section_games: "Meus Jogos",
        game_title: "Yodha: Tabuleiro de Batalha",
        game_description: "Um jogo de tabuleiro multiplayer online estratégico com mecânicas únicas.",
        footer: "© 2025 Dripredgames. Todos os direitos reservados.",
        // yodha.html translations
        yodha_title: "Yodha: Tabuleiro de Batalha",
        yodha_subtitle: "Jogo de Tabuleiro Multiplayer Estratégico Online",
        nav_home: "Início",
        nav_terms: "Termos e Condições",
        nav_privacy: "Política de Privacidade",
        section_yodha: "Yodha: Tabuleiro de Batalha",
        yodha_description: "Yodha: Tabuleiro de Batalha é nosso primeiro jogo de tabuleiro casual, localizado para suportar várias línguas em todo o mundo, oferecendo uma experiência multiplayer online estratégica e envolvente. Desafie jogadores globalmente com mecânicas únicas, como a funcionalidade 'sanduíche' protegida por direitos autorais. Estamos trabalhando ativamente em melhorias e atualizações de jogabilidade, com aprimoramentos emocionantes planejados para os próximos meses.",
        terms_title: "Termos e Condições",
        terms_updated: "Última Atualização: 14 de agosto de 2025",
        terms_intro: "Bem-vindo ao Yodha: Tabuleiro de Batalha ('o Aplicativo'), um jogo de tabuleiro multiplayer online casual e localizado desenvolvido pela Dripredgames ('nós' ou 'nosso'). Este é nosso primeiro jogo, projetado para ser acessível em várias línguas, com melhorias contínuas para otimizar a jogabilidade. Ao baixar, instalar ou usar o Aplicativo, você concorda em estar vinculado a estes Termos e Condições ('Termos'), que são armazenados localmente em seu dispositivo. Se você não concordar com estes Termos, por favor, não use o Aplicativo.",
        terms_acceptance: "Aceitação dos Termos",
        terms_acceptance_text: "Ao acessar ou usar o Aplicativo, você confirma que tem pelo menos 13 anos de idade (ou a idade mínima exigida em sua jurisdição para usar serviços online) e concorda em cumprir estes Termos. Se você tiver menos de 18 anos, deve ter o consentimento de um pai ou responsável legal para usar o Aplicativo.",
        privacy_title: "Política de Privacidade",
        privacy_updated: "Última Atualização: 14 de agosto de 2025",
        privacy_intro: "Dripredgames ('nós' ou 'nosso') está comprometida em proteger sua privacidade. Esta Política de Privacidade, armazenada localmente em seu dispositivo, explica como lidamos com as informações quando você usa o Yodha: Tabuleiro de Batalha ('o Aplicativo'), nosso primeiro jogo de tabuleiro casual, localizado para várias línguas em todo o mundo. Não coletamos, armazenamos ou compartilhamos nenhuma informação do usuário, incluindo IDs de convidado, mensagens de chat ou sessões de jogo, com nenhum banco de dados ou terceiros. Por favor, leia esta política com atenção. Se você não concordar com esta Política de Privacidade, por favor, não use o Aplicativo.",
        about_title: "Sobre Drip Red Games",
        about_subtitle: "Conectando o Mundo com Aventuras de Jogos de Tabuleiro Nunca Vistas",
        section_about: "Sobre o Desenvolvedor",
        about_description: "Olá, eu sou Alfred, o criador da Drip Red Games. Como introvertido, muitas vezes achei os encontros sociais desafiadores, sentindo-me deslocado em uma multidão. Isso me inspirou a me tornar um desenvolvedor de jogos independente, movido pela paixão de criar jogos de tabuleiro inovadores que oferecem uma experiência nova e envolvente. Meu objetivo é criar jogos que unam as pessoas, tragam alegria e proporcionem uma fuga de momentos sociais constrangedores, permitindo que os jogadores se conectem por meio de uma jogabilidade única e criativa. Se você tiver feedback ou ideias, entre em contato pelo <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Vamos criar algo extraordinário juntos!"
    },
    it: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Portare in vita giochi da tavolo online unici, mai visti prima, semplici e casual",
        nav_games: "I Miei Giochi",
        nav_about: "Sullo Sviluppatore",
        section_games: "I Miei Giochi",
        game_title: "Yodha: Tavolo da Battaglia",
        game_description: "Un gioco da tavolo multiplayer online strategico con meccaniche uniche.",
        footer: "© 2025 Dripredgames. Tutti i diritti riservati.",
        // yodha.html translations
        yodha_title: "Yodha: Tavolo da Battaglia",
        yodha_subtitle: "Gioco da Tavolo Multiplayer Strategico Online",
        nav_home: "Home",
        nav_terms: "Termini e Condizioni",
        nav_privacy: "Informativa sulla Privacy",
        section_yodha: "Yodha: Tavolo da Battaglia",
        yodha_description: "Yodha: Tavolo da Battaglia è il nostro primo gioco da tavolo casual, localizzato per supportare diverse lingue in tutto il mondo, offrendo un'esperienza multiplayer online strategica e coinvolgente. Sfida giocatori a livello globale con meccaniche uniche come la funzione 'sandwich' protetta da copyright. Stiamo lavorando attivamente a miglioramenti e aggiornamenti del gameplay, con entusiasmanti miglioramenti pianificati per i prossimi mesi.",
        terms_title: "Termini e Condizioni",
        terms_updated: "Ultimo aggiornamento: 14 agosto 2025",
        terms_intro: "Benvenuto in Yodha: Tavolo da Battaglia ('l'App'), un gioco da tavolo multiplayer online casual e localizzato sviluppato da Dripredgames ('noi' o 'nostro'). Questo è il nostro primo gioco, progettato per essere accessibile in diverse lingue, con continui miglioramenti per ottimizzare il gameplay. Scaricando, installando o utilizzando l'App, accetti di essere vincolato da questi Termini e Condizioni ('Termini'), che vengono memorizzati localmente sul tuo dispositivo. Se non sei d'accordo con questi Termini, ti preghiamo di non utilizzare l'App.",
        terms_acceptance: "Accettazione dei Termini",
        terms_acceptance_text: "Accedendo o utilizzando l'App, confermi di avere almeno 13 anni (o l'età minima richiesta nella tua giurisdizione per utilizzare servizi online) e accetti di rispettare questi Termini. Se hai meno di 18 anni, devi avere il consenso di un genitore o tutore legale per utilizzare l'App.",
        privacy_title: "Informativa sulla Privacy",
        privacy_updated: "Ultimo aggiornamento: 14 agosto 2025",
        privacy_intro: "Dripredgames ('noi' o 'nostro') si impegna a proteggere la tua privacy. Questa Informativa sulla Privacy, memorizzata localmente sul tuo dispositivo, spiega come gestiamo le informazioni quando utilizzi Yodha: Tavolo da Battaglia ('l'App'), il nostro primo gioco da tavolo casual, localizzato per diverse lingue in tutto il mondo. Non raccogliamo, memorizziamo o condividiamo alcuna informazione dell'utente, inclusi ID ospite, messaggi di chat o sessioni di gioco, con database o terze parti. Ti preghiamo di leggere attentamente questa informativa. Se non sei d'accordo con questa Informativa sulla Privacy, ti preghiamo di non utilizzare l'App.",
        about_title: "Su Drip Red Games",
        about_subtitle: "Collegare il mondo con avventure di giochi da tavolo mai viste prima",
        section_about: "Sullo Sviluppatore",
        about_description: "Ciao, sono Alfred, il creatore di Drip Red Games. Come introverso, ho spesso trovato le riunioni sociali difficili, sentendomi fuori posto in mezzo alla folla. Questo mi ha ispirato a diventare uno sviluppatore di giochi indipendente, spinto dalla passione di progettare giochi da tavolo innovativi che offrono un'esperienza fresca e coinvolgente. Il mio obiettivo è creare giochi che uniscano le persone, portino gioia e offrano una fuga da momenti sociali imbarazzanti, permettendo ai giocatori di connettersi attraverso un gameplay unico e creativo. Se hai feedback o idee, contattami a <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Creiamo qualcosa di straordinario insieme!"
    },
    ko: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "독특하고, 처음 보는, 간단하고 캐주얼한 온라인 보드 게임을 구현하다",
        nav_games: "내 게임",
        nav_about: "개발자 소개",
        section_games: "내 게임",
        game_title: "요다: 배틀 보드",
        game_description: "독특한 메커니즘을 가진 전략적인 온라인 멀티플레이어 보드 게임.",
        footer: "© 2025 Dripredgames. 모든 권리 보유.",
        // yodha.html translations
        yodha_title: "요다: 배틀 보드",
        yodha_subtitle: "전략적인 온라인 멀티플레이어 보드 게임",
        nav_home: "홈",
        nav_terms: "이용 약관",
        nav_privacy: "개인정보 보호정책",
        section_yodha: "요다: 배틀 보드",
        yodha_description: "요다: 배틀 보드는 전 세계 여러 언어를 지원하도록 현지화된 우리의 첫 번째 캐주얼 보드 게임으로, 전략적이고 몰입감 있는 온라인 멀티플레이어 경험을 제공합니다. 저작권으로 보호된 '샌드위치' 기능과 같은 독특한 메커니즘으로 전 세계 플레이어들과 경쟁하세요. 우리는 게임플레이 개선과 업데이트를 적극적으로 진행 중이며, 앞으로 몇 달 동안 흥미로운 개선 사항을 계획하고 있습니다.",
        terms_title: "이용 약관",
        terms_updated: "최종 업데이트: 2025년 8월 14일",
        terms_intro: "요다: 배틀 보드('앱')에 오신 것을 환영합니다. 이는 Dripredgames('우리' 또는 '당사')가 개발한 캐주얼하고 현지화된 온라인 멀티플레이어 보드 게임입니다. 이것은 여러 언어로 접근 가능하도록 설계된 우리의 첫 번째 게임으로, 게임플레이를 최적화하기 위해 지속적인 개선이 이루어지고 있습니다. 앱을 다운로드, 설치 또는 사용함으로써, 귀하는 이 이용 약관('약관')에 구속되는 데 동의하며, 이 약관은 귀하의 기기에 로컬로 저장됩니다. 이 약관에 동의하지 않으면 앱을 사용하지 마십시오.",
        terms_acceptance: "약관 수락",
        terms_acceptance_text: "앱에 접근하거나 사용함으로써, 귀하는 최소 13세 이상(또는 귀하의 관할권에서 온라인 서비스를 사용하기 위해 요구되는 최소 연령)이며 이 약관을 준수하는 데 동의함을 확인합니다. 18세 미만인 경우, 앱을 사용하려면 부모 또는 법적 보호자의 동의를 받아야 합니다.",
        privacy_title: "개인정보 보호정책",
        privacy_updated: "최종 업데이트: 2025년 8월 14일",
        privacy_intro: "Dripredgames('우리' 또는 '당사')는 귀하의 개인정보 보호에 전념합니다. 이 개인정보 보호정책은 귀하의 기기에 로컬로 저장되며, 요다: 배틀 보드('앱') 사용 시 정보를 어떻게 처리하는지 설명합니다. 이는 전 세계 여러 언어를 지원하도록 현지화된 우리의 첫 번째 캐주얼 보드 게임입니다. 우리는 게스트 ID, 채팅 메시지, 게임 세션을 포함한 어떠한 사용자 정보도 데이터베이스나 제3자와 수집, 저장 또는 공유하지 않습니다. 이 정책을 주의 깊게 읽어주십시오. 이 개인정보 보호정책에 동의하지 않으면 앱을 사용하지 마십시오.",
        about_title: "Drip Red Games 소개",
        about_subtitle: "독특한 보드 게임 모험으로 세상을 연결하다",
        section_about: "개발자 소개",
        about_description: "안녕하세요, 저는 Drip Red Games의 창립자 알프레드입니다. 내성적인 성격 때문에 사교 모임에서 종종 어려움을 겪었고, 군중 속에서 어색함을 느꼈습니다. 이것이 저를 독립적인 게임 개발자로 만들었고, 혁신적인 보드 게임을 디자인하여 새롭고 몰입감 있는 경험을 제공하려는 열정에 이끌렸습니다. 제 목표는 사람들을 하나로 모으고, 기쁨을 주며, 어색한 사교적 순간에서 벗어날 수 있는 게임을 만들어, 독특하고 창의적인 게임플레이를 통해 플레이어들이 연결되도록 하는 것입니다. 피드백이나 아이디어가 있다면 <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>으로 연락주세요. 함께 특별한 것을 만들어봅시다!"
    },
    tr: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Benzersiz, daha önce görülmemiş, basit ve rahat çevrimiçi masa oyunlarını hayata geçirmek",
        nav_games: "Oyunlarım",
        nav_about: "Geliştirici Hakkında",
        section_games: "Oyunlarım",
        game_title: "Yodha: Savaş Tahtası",
        game_description: "Benzersiz mekaniklere sahip stratejik bir çevrimiçi çok oyunculu masa oyunu.",
        footer: "© 2025 Dripredgames. Tüm hakları saklıdır.",
        // yodha.html translations
        yodha_title: "Yodha: Savaş Tahtası",
        yodha_subtitle: "Stratejik Çevrimiçi Çok Oyunculu Masa Oyunu",
        nav_home: "Ana Sayfa",
        nav_terms: "Kullanım Şartları",
        nav_privacy: "Gizlilik Politikası",
        section_yodha: "Yodha: Savaş Tahtası",
        yodha_description: "Yodha: Savaş Tahtası, dünya genelinde birden fazla dili desteklemek için yerelleştirilmiş ilk rahat masa oyunumuzdur ve stratejik ve etkileyici bir çevrimiçi çok oyunculu deneyim sunar. Telif hakkıyla korunan 'sandviç' özelliği gibi benzersiz mekaniklerle dünya çapındaki oyunculara meydan okuyun. Oynanış iyileştirmeleri ve güncellemeler üzerinde aktif olarak çalışıyoruz ve önümüzdeki aylar için heyecan verici geliştirmeler planlanıyor.",
        terms_title: "Kullanım Şartları",
        terms_updated: "Son Güncelleme: 14 Ağustos 2025",
        terms_intro: "Yodha: Savaş Tahtası'na ('Uygulama') hoş geldiniz, Dripredgames ('biz' veya 'bizim') tarafından geliştirilen rahat ve yerelleştirilmiş bir çevrimiçi çok oyunculu masa oyunudur. Bu, birden fazla dilde erişilebilir olacak şekilde tasarlanmış ilk oyunumuzdur ve oynanışı optimize etmek için sürekli iyileştirmeler yapılmaktadır. Uygulamayı indirerek, kurarak veya kullanarak, cihazınızda yerel olarak depolanan bu Kullanım Şartları'na ('Şartlar') bağlı olmayı kabul edersiniz. Bu Şartlar'a katılmıyorsanız, lütfen Uygulamayı kullanmayın.",
        terms_acceptance: "Şartların Kabulü",
        terms_acceptance_text: "Uygulamaya erişerek veya kullanarak, en az 13 yaşında olduğunuzu (veya bölgenizde çevrimiçi hizmetleri kullanmak için gerekli minimum yaşta olduğunuzu) ve bu Şartlar'a uymayı kabul ettiğinizi onaylarsınız. 18 yaşından küçükseniz, Uygulamayı kullanmak için bir ebeveyn veya yasal vasinin iznini almalısınız.",
        privacy_title: "Gizlilik Politikası",
        privacy_updated: "Son Güncelleme: 14 Ağustos 2025",
        privacy_intro: "Dripredgames ('biz' veya 'bizim') gizliliğinizi korumaya kararlıdır. Cihazınızda yerel olarak depolanan bu Gizlilik Politikası, dünya genelinde birden fazla dil için yerelleştirilmiş ilk rahat masa oyunumuz olan Yodha: Savaş Tahtası'nı ('Uygulama') kullanırken bilgilerinizi nasıl işlediğimizi açıklar. Misafir kimlikleri, sohbet mesajları veya oyun oturumları dahil hiçbir kullanıcı bilgisini herhangi bir veritabanı veya üçüncü taraflarla toplamıyor, saklamıyor veya paylaşmıyor. Lütfen bu politikayı dikkatlice okuyun. Bu Gizlilik Politikası'na katılmıyorsanız, lütfen Uygulamayı kullanmayın.",
        about_title: "Drip Red Games Hakkında",
        about_subtitle: "Dünyayı Daha Önce Görülmemiş Masa Oyunu Maceralarıyla Birleştirmek",
        section_about: "Geliştirici Hakkında",
        about_description: "Merhaba, ben Drip Red Games'in yaratıcısı Alfred. İçe dönük biri olarak, sosyal toplantıları genellikle zorlayıcı buldum ve kalabalıkta kendimi yersiz hissettim. Bu, bağımsız bir oyun geliştiricisi olmamı teşvik etti ve yenilikçi masa oyunları tasarlamaya olan tutkum, taze ve etkileyici bir deneyim sunmama yön verdi. Amacım, insanları bir araya getiren, neşe getiren ve sosyal olarak rahatsız edici anlardan kaçış sağlayan oyunlar yaratmak, oyuncuların benzersiz ve yaratıcı oynanış yoluyla bağlantı kurmasını sağlamaktır. Geri bildirim veya fikirleriniz varsa, <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a> adresinden bana ulaşın. Birlikte olağanüstü bir şeyler yaratalım!"
    },
    nl: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Unieke, nog nooit eerder geziene, eenvoudige en casual online bordspellen tot leven brengen",
        nav_games: "Mijn Spellen",
        nav_about: "Over de Ontwikkelaar",
        section_games: "Mijn Spellen",
        game_title: "Yodha: Strijdbord",
        game_description: "Een strategisch online multiplayer bordspel met unieke mechanismen.",
        footer: "© 2025 Dripredgames. Alle rechten voorbehouden.",
        // yodha.html translations
        yodha_title: "Yodha: Strijdbord",
        yodha_subtitle: "Strategisch Online Multiplayer Bordspel",
        nav_home: "Home",
        nav_terms: "Voorwaarden",
        nav_privacy: "Privacybeleid",
        section_yodha: "Yodha: Strijdbord",
        yodha_description: "Yodha: Strijdbord is ons eerste casual bordspel, gelokaliseerd om meerdere talen wereldwijd te ondersteunen, en biedt een strategische en boeiende online multiplayer-ervaring. Daag spelers wereldwijd uit met unieke mechanismen zoals de auteursrechtelijk beschermde 'sandwich'-functie. We werken actief aan verbeteringen en updates van de gameplay, met spannende verbeteringen gepland voor de komende maanden.",
        terms_title: "Voorwaarden",
        terms_updated: "Laatst bijgewerkt: 14 augustus 2025",
        terms_intro: "Welkom bij Yodha: Strijdbord ('de App'), een casual en gelokaliseerd online multiplayer bordspel ontwikkeld door Dripredgames ('wij' of 'ons'). Dit is ons eerste spel, ontworpen om toegankelijk te zijn in meerdere talen, met voortdurende verbeteringen om de gameplay te optimaliseren. Door de App te downloaden, te installeren of te gebruiken, ga je akkoord met deze Voorwaarden ('Voorwaarden'), die lokaal op je apparaat worden opgeslagen. Als je niet akkoord gaat met deze Voorwaarden, gebruik de App dan niet.",
        terms_acceptance: "Acceptatie van de Voorwaarden",
        terms_acceptance_text: "Door de App te gebruiken of te openen, bevestig je dat je minimaal 13 jaar oud bent (of de minimumleeftijd die in jouw rechtsgebied vereist is om online diensten te gebruiken) en ga je akkoord met het naleven van deze Voorwaarden. Als je jonger bent dan 18 jaar, moet je toestemming hebben van een ouder of wettelijke voogd om de App te gebruiken.",
        privacy_title: "Privacybeleid",
        privacy_updated: "Laatst bijgewerkt: 14 augustus 2025",
        privacy_intro: "Dripredgames ('wij' of 'ons') is toegewijd aan het beschermen van jouw privacy. Dit Privacybeleid, lokaal opgeslagen op je apparaat, legt uit hoe we omgaan met informatie wanneer je Yodha: Strijdbord ('de App') gebruikt, ons eerste casual bordspel, gelokaliseerd voor meerdere talen wereldwijd. We verzamelen, bewaren of delen geen gebruikersinformatie, inclusief gast-ID's, chatberichten of spelsessies, met databases of derden. Lees dit beleid zorgvuldig door. Als je niet akkoord gaat met dit Privacybeleid, gebruik de App dan niet.",
        about_title: "Over Drip Red Games",
        about_subtitle: "De wereld verbinden met ongeziene bordspelavonturen",
        section_about: "Over de Ontwikkelaar",
        about_description: "Hoi, ik ben Alfred, de maker van Drip Red Games. Als introvert vond ik sociale bijeenkomsten vaak uitdagend en voelde ik me niet op mijn plek in een menigte. Dit inspireerde me om een onafhankelijke game-ontwikkelaar te worden, gedreven door een passie om innovatieve bordspellen te ontwerpen die een frisse en boeiende ervaring bieden. Mijn doel is om spellen te maken die mensen samenbrengen, vreugde brengen en een ontsnapping bieden uit ongemakkelijke sociale momenten, waardoor spelers kunnen verbinden via unieke en creatieve gameplay. Als je feedback of ideeën hebt, neem contact op via <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Laten we samen iets bijzonders creëren!"
    },
    sv: {
        title: "Dripredgames",
        header_title: "Dripredgames",
        header_subtitle: "Att ge liv åt unika, aldrig tidigare skådade, enkla och avslappnade online-brädspel",
        nav_games: "Mina Spel",
        nav_about: "Om Utvecklaren",
        section_games: "Mina Spel",
        game_title: "Yodha: Stridsbräde",
        game_description: "Ett strategiskt online-multiplayer-brädspel med unika mekanismer.",
        footer: "© 2025 Dripredgames. Alla rättigheter förbehållna.",
        // yodha.html translations
        yodha_title: "Yodha: Stridsbräde",
        yodha_subtitle: "Strategiskt Online-Multiplayer-Brädspe",
        nav_home: "Hem",
        nav_terms: "Villkor",
        nav_privacy: "Integritetspolicy",
        section_yodha: "Yodha: Stridsbräde",
        yodha_description: "Yodha: Stridsbräde är vårt första avslappnade brädspel, lokaliserat för att stödja flera språk världen över, och erbjuder en strategisk och engagerande online-multiplayer-upplevelse. Utmana spelare globalt med unika mekanismer som den upphovsrättsskyddade 'sandwich'-funktionen. Vi arbetar aktivt med förbättringar och uppdateringar av spelet, med spännande förbättringar planerade för de kommande månaderna.",
        terms_title: "Villkor",
        terms_updated: "Senast uppdaterad: 14 augusti 2025",
        terms_intro: "Välkommen till Yodha: Stridsbräde ('Appen'), ett avslappnat och lokaliserat online-multiplayer-brädspel utvecklat av Dripredgames ('vi' eller 'oss'). Detta är vårt första spel, utformat för att vara tillgängligt på flera språk, med kontinuerliga förbättringar för att optimera spelupplevelsen. Genom att ladda ner, installera eller använda Appen godkänner du att vara bunden av dessa Villkor ('Villkor'), som lagras lokalt på din enhet. Om du inte godkänner dessa Villkor, använd inte Appen.",
        terms_acceptance: "Godkännande av Villkor",
        terms_acceptance_text: "Genom att använda eller få åtkomst till Appen bekräftar du att du är minst 13 år gammal (eller den minimiålder som krävs i din jurisdiktion för att använda online-tjänster) och samtycker till att följa dessa Villkor. Om du är under 18 år måste du ha samtycke från en förälder eller vårdnadshavare för att använda Appen.",
        privacy_title: "Integritetspolicy",
        privacy_updated: "Senast uppdaterad: 14 augusti 2025",
        privacy_intro: "Dripredgames ('vi' eller 'oss') är engagerade i att skydda din integritet. Denna Integritetspolicy, lagrad lokalt på din enhet, förklarar hur vi hanterar information när du använder Yodha: Stridsbräde ('Appen'), vårt första avslappnade brädspel, lokaliserat för flera språk världen över. Vi samlar inte in, lagrar eller delar någon användarinformation, inklusive gäst-ID:n, chattmeddelanden eller spelsessioner, med databaser eller tredje parter. Vänligen läs denna policy noggrant. Om du inte godkänner denna Integritetspolicy, använd inte Appen.",
        about_title: "Om Drip Red Games",
        about_subtitle: "Att förena världen med osedda brädspelsäventyr",
        section_about: "Om Utvecklaren",
        about_description: "Hej, jag är Alfred, skaparen av Drip Red Games. Som introvert har jag ofta funnit sociala sammankomster utmanande och känt mig malplacerad i en folkmassa. Detta inspirerade mig att bli en oberoende spelutvecklare, driven av en passion för att designa innovativa brädspel som erbjuder en fräsch och engagerande upplevelse. Mitt mål är att skapa spel som för människor samman, sprider glädje och erbjuder en flykt från besvärliga sociala ögonblick, så att spelare kan koppla samman genom unikt och kreativt spelande. Om du har feedback eller idéer, kontakta mig på <a href='mailto:dripredgames@gmail.com'>dripredgames@gmail.com</a>. Låt oss skapa något extraordinärt tillsammans!"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('language', lang);
    updateContent(lang);
}

function updateContent(lang) {
    // Fallback to English if the selected language is missing translations
    const translation = translations[lang] && Object.keys(translations[lang]).length > 0 ? translations[lang] : translations['en'];

    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translation[key]) {
            // Handle elements with HTML content (e.g., links)
            if (element.innerHTML.includes('<a')) {
                element.innerHTML = translation[key];
            } else {
                element.textContent = translation[key];
            }
        } else {
            // Fallback to English if translation for the key is missing
            if (translations['en'][key]) {
                if (element.innerHTML.includes('<a')) {
                    element.innerHTML = translations['en'][key];
                } else {
                    element.textContent = translations['en'][key];
                }
            }
        }
    });
    document.documentElement.lang = lang;
    document.title = translation.title || translations['en'].title || 'Dripredgames';
}

function initializeLanguage() {
    const savedLang = localStorage.getItem('language') || 'en';
    document.getElementById('language-select').value = savedLang;
    updateContent(savedLang);
}